- name: Установка и конфигурирование PostgreSQL на Debain 11
  hosts: debian_server
  become: true
  tasks:

    - name: Обновление кэша APT
      apt:
        update_cache: yes

    - name: Загрузка ключа GPG
      get_url:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        dest: /tmp/postgresql-key.asc

    - name: Добавление ключа подписи GPG в keyring
      command: >
        gpg --dearmor -o /usr/share/keyrings/postgresql-keyring.gpg /tmp/postgresql-key.asc
      args:
        creates: /usr/share/keyrings/postgresql-keyring.gpg

    - name: Добавление репозитория PostgreSQL
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/postgresql-keyring.gpg] http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
        filename: 'postgresql'
        state: present

    - name: Обновление списка пакетов
      apt:
        update_cache: yes

    - name: Установка PostgreSQL 16 версии
      apt:
        name: 
          - postgresql-16
          - python3
          - python3-psycopg2
        state: present

    - name: Запуск и включение службы PostgreSQL
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Настройка PostgreSQL для прослушивания всех интерфейсов
      lineinfile:
        path: /etc/postgresql/16/main/postgresql.conf
        regexp: '^#?listen_addresses ='
        line: "listen_addresses = '*'"
        state: present

    - name: Настройка удаленных подключений к PostgreSQL
      lineinfile:
        path: /etc/postgresql/16/main/pg_hba.conf
        line: 'host all all 0.0.0.0/0 md5'
        state: present

    - name: Настройка метода аутентификации на trust для postgres в pg_hba.conf
      lineinfile:
        path: /etc/postgresql/16/main/pg_hba.conf
        regexp: '^local\s+all\s+postgres'
        line: 'local    all             postgres                                trust'
        state: present
      notify: Restart PostgreSQL

    - name: Установка пароля для пользователя "postgres"
      community.postgresql.postgresql_user:
        name: postgres
        password: "1"
        state: present
        login_user: postgres

    - name: Настройка метода аутентификации на md5 для postgres в pg_hba.conf
      lineinfile:
        path: /etc/postgresql/16/main/pg_hba.conf
        regexp: '^local\s+all\s+postgres'
        line: 'local    all             postgres                                md5'
        state: present
      notify: Restart PostgreSQL

    - name: Создание базы данных "test_db"
      community.postgresql.postgresql_db:
        name: test_db
        state: present
        login_user: postgres
        login_password: "1"  

    - name: Создание пользователя "db_user"
      community.postgresql.postgresql_user:
        name: db_user
        password: "12345"
        db: test_db
        priv: "ALL"
        state: present
        login_user: postgres
        login_password: "1"

    - name: Создание таблицы "test_table"
      community.postgresql.postgresql_query:
        db: test_db
        query: |
          CREATE TABLE IF NOT EXISTS test_table (
            id SERIAL PRIMARY KEY,
            name VARCHAR(50),
            age INT
          );
        login_user: postgres
        login_password: "1"

    - name: Внесение тестовых данных в "test_table"
      community.postgresql.postgresql_query:
        db: test_db
        query: |
          INSERT INTO test_table (name, age) VALUES
          ('Alice', 30),
          ('Bob', 25),
          ('Charlie', 35);
        login_user: postgres
        login_password: "1"

  handlers:
    - name: Перезагрузка PostgreSQL
      service:
        name: postgresql
        state: restarted
