- name: Установка и конфигурирование PostgreSQL на Debian 11
  hosts: debian_server
  become: true
  tasks:
    - name: Обновление кэша APT
      apt:
        update_cache: yes

    - name: Установка часового пояса
      timezone:
        name: "Europe/Moscow"

    - name: Установка chrony для синхронизации времени
      apt:
        name: chrony
        state: present

    - name: Включение chrony
      service:
        name: chrony
        state: started
        enabled: yes

    - name: Установка сетевых утилит
      apt:
        name:
          - net-tools
          - curl
          - traceroute
          - telnet
          - iproute2
        state: present

    - name: Запрет root-входа через SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'
        
    - name: Отключение аутентификации по паролю для SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'

    - name: Установка fail2ban
      apt:
        name: fail2ban
        state: present

    - name: Настройка fail2ban для защиты SSH
      lineinfile:
        path: /etc/fail2ban/jail.local
        create: yes
        line: |
          [sshd]
          enabled = true
          maxretry = 5
          bantime = 3600

    - name: Перезагрузка SSH
      service:
        name: ssh
        state: restarted

    - name: Перезагрузка fail2ban
      service:
        name: fail2ban
        state: restarted
        
    - name: Настройка параметров sysctl
      ansible.builtin.sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      loop:
        - { name: "net.ipv4.ip_forward", value: "1" }
        - { name: "vm.swappiness", value: "10" }
        - { name: "fs.file-max", value: "100000" }
        - { name: "net.core.somaxconn", value: "1024" }
        - { name: "net.ipv4.tcp_max_syn_backlog", value: "2048" }

    - name: Сохранение настроек sysctl
      ansible.builtin.command: sysctl -p

    - name: Загрузка ключа GPG PostgreSQL
      get_url:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        dest: /tmp/postgresql-key.asc

    - name: Добавление ключа подписи GPG в keyring
      command: >
        gpg --dearmor -o /usr/share/keyrings/postgresql-keyring.gpg /tmp/postgresql-key.asc
      args:
        creates: /usr/share/keyrings/postgresql-keyring.gpg

    - name: Добавление репозитория PostgreSQL
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/postgresql-keyring.gpg] http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
        filename: 'postgresql'
        state: present

    - name: Обновление списка пакетов
      apt:
        update_cache: yes

    - name: Установка PostgreSQL 16 версии
      apt:
        name: 
          - postgresql-16
          - python3
          - python3-psycopg2
        state: present

    - name: Запуск и включение службы PostgreSQL
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: Настройка PostgreSQL для прослушивания всех интерфейсов
      lineinfile:
        path: /etc/postgresql/16/main/postgresql.conf
        regexp: '^#?listen_addresses ='
        line: "listen_addresses = '*'"
        state: present

    - name: Настройка удаленных подключений к PostgreSQL
      lineinfile:
        path: /etc/postgresql/16/main/pg_hba.conf
        line: 'host all all 0.0.0.0/0 md5'
        state: present

    - name: Настройка метода аутентификации для postgres в pg_hba.conf
      block:
        - name: Настройка метода аутентификации на trust для postgres в pg_hba.conf
          lineinfile:
            path: /etc/postgresql/16/main/pg_hba.conf
            regexp: '^local\s+all\s+postgres'
            line: 'local    all             postgres                                trust'
            state: present

        - name: Установка пароля для пользователя "postgres"
          community.postgresql.postgresql_user:
            name: postgres
            password: "1"
            state: present
            login_user: postgres
    
        - name: Настройка метода аутентификации на md5 для postgres в pg_hba.conf
          lineinfile:
            path: /etc/postgresql/16/main/pg_hba.conf
            regexp: '^local\s+all\s+postgres'
            line: 'local    all             postgres                                md5'
            state: present

    - name: Перезагрузка PostgreSQL
      service:
        name: postgresql
        state: restarted

    - name: Создание базы данных "test_db"
      community.postgresql.postgresql_db:
        name: test_db
        state: present
        login_user: postgres
        login_password: "1"  

    - name: Создание пользователя "db_user"
      community.postgresql.postgresql_user:
        name: db_user
        password: "12345"
        db: test_db
        priv: "ALL"
        state: present
        login_user: postgres
        login_password: "1"

    - name: Создание таблицы "test_table"
      community.postgresql.postgresql_query:
        db: test_db
        query: |
          CREATE TABLE IF NOT EXISTS test_table (
            id SERIAL PRIMARY KEY,
            name VARCHAR(50),
            age INT
          );
        login_user: postgres
        login_password: "1"

    - name: Внесение тестовых данных в "test_table"
      community.postgresql.postgresql_query:
        db: test_db
        query: |
          INSERT INTO test_table (name, age) VALUES
          ('Alice', 30),
          ('Bob', 25),
          ('Charlie', 35);
        login_user: postgres
        login_password: "1"
